/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package discworldgurps.details;

import javax.swing.JOptionPane;

/**
 *
 * @author mageg
 */
public class Reputation extends javax.swing.JDialog {

    public int closed = 0;
    private double repLvlCost, repAffCost, repFrqCost;
    private String repMod;
    private int repCost;
    private String repDesc;
    Details details = new Details();
    private static String ad;

    /**
     * Creates new form Rep
     */
    public Reputation(java.awt.Frame parent, boolean modal, String ad) {
        super(parent, modal);
        initComponents();
        this.ad = ad;
        if ("d".equals(this.ad)) {
            jComboBoxRepLvl.removeAllItems();
            jComboBoxRepLvl.addItem("Reputation - 1");
            jComboBoxRepLvl.addItem("Reputation - 2");
            jComboBoxRepLvl.addItem("Reputation - 3");
            jComboBoxRepLvl.addItem("Reputation - 4");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxRepLvl = new javax.swing.JComboBox<>();
        jComboBoxRepAff = new javax.swing.JComboBox<>();
        jComboBoxRepFrq = new javax.swing.JComboBox<>();
        jTextFieldRepDesc = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reputation Level");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("People Affected");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Frequency");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Description");

        jComboBoxRepLvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reputation + 1", "Reputation + 2", "Reputation + 3", "Reputation + 4" }));

        jComboBoxRepAff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almost Everyone", "AE except a Large Class", "Large Class", "Small Class" }));

        jComboBoxRepFrq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All The Time", "Occasionally", "Sometimes" }));

        jButtonAdd.setText("Add");
        jButtonAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldRepDesc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRepLvl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRepAff, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxRepFrq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRepLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRepAff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRepFrq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRepDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        closed = 1;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closed = 1;
    }//GEN-LAST:event_formWindowClosing

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        switch (jComboBoxRepLvl.getSelectedIndex()) {
            case 0:
                repLvlCost = 5;
                repMod = "1";
                break;
            case 1:
                repLvlCost = 10;
                repMod = "2";
                break;
            case 2:
                repLvlCost = 15;
                repMod = "3";
                break;
            case 3:
                repLvlCost = 20;
                repMod = "4";
                break;
            default:
                break;
        }
        switch (jComboBoxRepAff.getSelectedIndex()) {
            case 0:
                repAffCost = 1;
                break;
            case 1:
                repAffCost = 0.67;
                break;
            case 2:
                repAffCost = 0.5;
                break;
            case 3:
                repAffCost = 0.34;
                break;
            default:
                break;
        }
        switch (jComboBoxRepFrq.getSelectedIndex()) {
            case 0:
                repFrqCost = 1;
                break;
            case 1:
                repFrqCost = 0.5;
                break;
            case 2:
                repFrqCost = 0.34;
                break;
            default:
                break;
        }
        if ("".equals(jTextFieldRepDesc.getText())){
            JOptionPane.showMessageDialog(null, "You didn't enter a description!", "You silly goose!", JOptionPane.ERROR_MESSAGE);
        } else {
        if ("d".equals(this.ad)) {
            repCost = (int) ((-repLvlCost * repAffCost) * repFrqCost);
            if (repCost > -1) {
                repCost = -1;
            }
            repDesc = String.format("Rep: %s (Mod: -%s | Freq: %s)", jTextFieldRepDesc.getText(), repMod, jComboBoxRepFrq.getSelectedItem().toString());
        } else {
            repCost = (int) ((repLvlCost * repAffCost) * repFrqCost);
            if (repCost < 1) {
                repCost = 1;
            }
            repDesc = String.format("Rep: %s (Mod: +%s | Freq: %s)", jTextFieldRepDesc.getText(), repMod, jComboBoxRepFrq.getSelectedItem().toString());
        }
        dispose();
        }

        
        

    }//GEN-LAST:event_jButtonAddActionPerformed

    public String getRepCost() {
        return String.format("%d", repCost);
    }

    public String getRepDesc() {
        return repDesc;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reputation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reputation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reputation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reputation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reputation dialog = new Reputation(new javax.swing.JFrame(), true, ad);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<String> jComboBoxRepAff;
    private javax.swing.JComboBox<String> jComboBoxRepFrq;
    private javax.swing.JComboBox<String> jComboBoxRepLvl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldRepDesc;
    // End of variables declaration//GEN-END:variables
}
